### PR TITLE
Fix urls to remove Django 1.9 warnings

### PR DESCRIPTION
**Pull request by douglas**

### CODE REVIEW

**Comment by aaugustin** [comment]
This is pretty much a duplicate of #138.

**Comment by douglas** [comment]
Thank you, @aaugustin ! Hope to have your changes merged asap =)

**Comment by aaugustin** [comment]
Actually the maintainer may choose to merge your version which is slightly more complete. Up to them!

**Comment by selwin** [comment]
Version 0.9 is now on PyPI: https://pypi.python.org/pypi/django-rq

**Comment by aaugustin** [comment]
Thanks a lot @selwin!

**Pull request closed without merging**
