### PR TITLE
Queues are not passed via command line

### LINKED ISSUE #180: Queues are not passed via command line
There is a missing `parser.add_argument('queues', nargs='+', type=str)` line. Now if I execute this (as documented):

    manage.py rqworker high default low

I get the error:

    manage.py rqworker: error: unrecognized arguments: high default low

### PR DESCRIPTION
**Pull request by hendi**
This fixes #180 on Django 1.10

### CODE REVIEW

**Comment by Wingie** [comment]
can this be merged into base branch?

**Comment by selwin** [comment]
Thanks!

**Comment by psyonara** [comment]
Can a new release be created for this change? Or is there a different way of specifying queues for the rqworker command? I upgraded to Django 1.10, but can't start the worker for specific queues now.

**Comment by Wingie** [comment]
you can specify the git repo in the requirements.txt and run `pip install
-r requirements.txt --upgrade` until a release exists.

[Wilson Wingston Sharon]

**Comment by psyonara** [comment]
Ok, just wanted to check if there's another way, since I'd prefer not to do it that way on a production server. Thanks!

**Comment by dieb** [comment]
Thanks for fixing it!

**Comment by eriktelepovsky** [comment]
It does not work in Django==1.9

**Comment by starenka** [comment]
Indeed it does not work on Django 1.9

**Comment by selwin** [comment]
@eriktelepovsky mind opening a PR to fix this on Django 1.9? The easiest way would be to check the Django version and falls back to the old mechanism for Django < 1.10

**Comment by eriktelepovsky** [comment]
@selwin I am not familiar with the old mechanism or the difference between Django 1.9 and 1.10 command management. Maybe @hendi will know better.

**Comment by hendi** [comment]
I'll have a look!

**Comment by hendi** [comment]
@starenka Fixed in #199

**Pull request merged**
